Task/Implement notification layer
jv-feb24-group-project5/booking-app pull request #13
Opened 2024-06-02 09:33 UTC by TonyH277

2024-06-02 18:47 UTC, MolchanovAlexander requested changes

2024-06-02 18:47 UTC, MolchanovAlexander commented on src/main/resources/application.properties
> +telegram.bot.group.id=${GROUP_ID}
Suggest you to add TELEGRAM three times before its variables names.

2024-06-02 18:47 UTC, MolchanovAlexander commented on src/main/resources/application.properties
> +telegram.bot.group.id=${GROUP_ID}
Suggest you to add TELEGRAM three times before its variables names.

2024-06-02 18:47 UTC, MolchanovAlexander commented on src/main/resources/application.properties
>  jwt.secret=${SECRET_KEY}
It is preferred to call them clearly.
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

2024-06-03 05:37 UTC, Nikname2303 requested changes
LGTM, just one minor comment

2024-06-03 05:37 UTC, Nikname2303 commented on Dockerfile
> +EXPOSE 8080
don't have last line, if you have it on your local version, just make indentation

2024-06-03 11:33 UTC, Nikname2303 approved these changes

2024-06-03 12:33 UTC, merged