added accomodation entitie with liquibase scripts
jv-feb24-group-project5/booking-app pull request #7
Opened 2024-05-30 15:14 UTC by VolandevlodD

2024-05-30 18:14 UTC, Nikname2303 approved these changes

2024-05-31 08:13 UTC, TonyH277 requested changes
Nice! Pls make changes so we have consistent code style. Consider having empty lines ind the end of file

2024-05-31 08:13 UTC, TonyH277 commented on src/main/java/com/ua/accommodation/model/Accommodation.java
> +@Data
Please change the getter and setter data
Optional: modify softDelete so that we have a consistent code style

2024-05-31 08:13 UTC, TonyH277 commented on src/main/java/com/ua/accommodation/model/Address.java
> +@Data
the same here

2024-05-31 08:13 UTC, TonyH277 commented on src/main/java/com/ua/accommodation/model/Amenity.java
> +@Data
the same here

2024-05-31 08:16 UTC, VolandevlodD commented on src/main/resources/application.properties
> -spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
Redundant
![image](https://github.com/jv-feb24-group-project5/booking-app/assets/124697095/27c9151c-33e4-40f0-91a0-2661dbacf94c)

2024-05-31 08:24 UTC, TonyH277 approved these changes

2024-05-31 08:24 UTC, TonyH277 commented on src/main/java/com/ua/accommodation/model/Accommodation.java
>  public class Accommodation {
```suggestion
@Entity
@Table(name = "accommodations")
@SQLDelete(sql = "UPDATE accommodations SET is_deleted = true WHERE id=?")
@SQLRestriction("is_deleted=false")
@Getter
@Setter
public class Accommodation {
```

2024-05-31 08:28 UTC, VolandevlodD commented on src/main/java/com/ua/accommodation/model/Accommodation.java
> +@SQLRestriction("is_deleted=false")
```suggestion
@SQLRestriction("is_deleted = false")
```

2024-05-31 08:32 UTC, merged